[package]
name = "memoir"
version = "0.1.0"
authors = ["Kan-Ru Chen <kanru@kanru.info>"]

[dependencies]
chrono = "0.2"
docopt = "0.6"
mustache = "0.6"
pulldown-cmark = "0.0.3"
rustc-serialize = "0.3"
walkdir = "0.1"
yaml-rust = "0.2"
